### ISSUE TITLE
Initiating a database

### ISSUE THREAD

**Issue by lhmarsden** [SIOS-Svalbard/Learnings_from_AeN_logging_system#21]
Vitaly Dekhtyarev noticed that it is sometimes not possible to initiate the database with the current setup. He writes

"When I run the app, it cannot start because it cannot initiate a db. The reason for that is getpass.getuser(). I use Windows machine and to run the app as Administrator, who does not have account in my Postgres DB.

I would suggest to use a config file with username or ask user for username instead of automatic insertion here."

**Comment by filchos** [comment]
@VitalyDek could you check with the new main branch, if the problem still exists?

getpass has been removed from the system. Instead a `config.json` is provided that can be edited locally.

**Comment by VitalyDek** [comment]
Hi @lhmarsden, yes I will check that.
