### ISSUE TITLE
Provide link to template generator in main nav

### ISSUE THREAD

**Issue by filchos** [SIOS-Svalbard/Learnings_from_AeN_logging_system#67]
When there is a configuration entry with a link to the standalone template generator, the main nav should provide a link there, preferably opening a new window.

Example for config:

```json
"templateGenerator": {
    "host": "https://127.0.0.1:9999"
}
```

**Comment by lhmarsden** [comment]
Fixed here: https://github.com/SIOS-Svalbard/Learnings_from_AeN_logging_system/commit/1e50fef5572684d1c1bdb60f5a985baf59912617
