### ISSUE TITLE
Integrate template generator as git submodule

### ISSUE THREAD

**Issue by filchos** [SIOS-Svalbard/Learnings_from_AeN_logging_system#68]
_open for discussion_

## Background

The new Logging System and Template Generator share some code concerning fields and Excel creation. Template Generator should run standalone.

## Solution

One of the possible solutions would be to integrate the Template Generator into the Logging System as a git submodule. Then duplicate code can be removed from the Template Generator and code from the Logging System can be used.

This makes the system more DRY.

----

Even though Template Generator is added as a submodule it will not run through the Logging System but on a distinct port. The Logging System UI will just provide a link there

**Comment by lhmarsden** [comment]
Fixed at this point: https://github.com/SIOS-Svalbard/Learnings_from_AeN_logging_system/commit/1e50fef5572684d1c1bdb60f5a985baf59912617
